const list = {
  'My Stuff': '我的主页',
  'Online Status': '在线状态',
  Profile: '个人资料',
  'Create Avatar': '创建头像',
  'User Settings': '用户设置',
  'User settings': '用户设置',
  'View Options': '查看选项',
  'Mod Mode': '版主模式',
  'Dark Mode': '夜间模式',
  'Create a Community': '创建社区',
  'Advertise on Reddit': '投放广告',
  Premium: '高级会员',
  Explore: '探索',
  Gaming: '游戏',
  Sports: '体育',
  'Business, Economics, and Finance': '商业、经济和金融',
  Crypto: '加密货币',
  Television: '电视',
  Celebrity: '名人',
  'More Topics': '更多主题',
  More: '更多',
  Rereddit: 'Rereddit',
  'Best Communities': '最佳社区',
  Communities: '社区',
  'About Reddit': '关于Reddit',
  Blog: '博客',
  Careers: '职业',
  Press: '新闻',
  'Visit Old Reddit': '旧版Reddit',
  'Terms & Policies': '条款和政策',
  'User Agreement': '用户协议',
  'Privacy Policy': '隐私政策',
  'Content Policy': '内容政策',
  'Moderator Code of Conduct': '社群守则',
  'Log Out': '退出登录',
  New: '最新',
  NEW: '最新',
  Hot: '热门',
  HOT: '热门',
  Top: '置顶',
  TOP: '置顶',
  OVERVIEW: '概览',
  Overview: '概览',
  COMMENTS: '评论',
  comments: '评论',
  HISTORY: '历史',
  SAVED: '已保存',
  HIDDEN: '隐藏',
  UPVOTED: '赞同',
  DOWNVOTED: '反对',
  'Create Post': '创建帖子',
  'Create Community': '创建社区',
  'Moderator Code Of Conduct': '社群守则',
  'Reddit Premium': 'Reddit高级会员',
  'The best Reddit experience': '最佳的Reddit体验',
  'Try Now': '立即尝试',
  Comments: '评论',
  Share: '分享',
  Save: '保存',
  'Back to Top': '回到顶部',
  "Because you've shown interest in a similar community": '因为您对类似社区表现出兴趣',
  Home: '主页',
  Join: '加入',
  Dec: '12月',
  Card: '卡片',
  CARD: '卡片',
  Classic: '经典',
  CLASSIC: '经典',
  Compact: '紧凑',
  COMPACT: '紧凑',
  'NEW USER SETTINGS': '新用户设置',
  'Like customizing Reddit?': '喜欢自定义Reddit吗？',
  'You can save how you sort and view your communities in user settings.': '您可以在用户设置中保存您对社区的排序和查看方式。',
  'Got it': '知道了',
  Advertise: '广告',
  'Create a post': '创建帖子',
  Post: '帖子',
  'Images & Video': '图片和视频',
  'Image & Video': '图片和视频',
  Link: '链接',
  Poll: '投票',
  'Drag and drop image or': '拖放图像或',
  Upload: '上传',
  'Send me post reply notifications': '发送给我帖子回复通知',
  Cancel: '取消',
  'Connect accounts to share your post': '连接账号以分享您的帖子',
  'This community does not allow original content tag': '本社区不允许原创内容标签',
  'This community does not allow spoiler tag': '本社区不允许剧透标签',
  'Mark as Not Safe For Work': '标记为不适于工作场所',
  'Select a subreddit to enable flair': '选择子社区以启用标识',
  Members: '成员',
  Online: '在线',
  'Ranked by Size': '按规模排名',
  'COMMUNITY OPTIONS': '社区选项',
  'Community options': '社区选项',
  'Community theme': '社区主题',
  'Save Draft': '保存草稿',
  DRAFTS: '草稿',
  Drafts: '草稿',
  'Mark as a spoiler': '标记为剧透',
  'Add flair': '添加标识',
  PREVIEW: '预览',
  preview: '预览',
  Created: '创建于',
  'Show More Posts Like This': '显示更多类似帖子',
  'Show Fewer Posts Like This': '显示更少类似帖子',
  Hide: '隐藏',
  Report: '举报',
  Rising: '热度上升',
  RISING: '热度上升',
  Best: '最佳',
  Reply: '回复',
  Joined: '已加入',
  'Sort By: Best': '按 最佳 排序',
  'Sort By: Top': '按 热门 排序',
  'Sort By: New': '按 最新 排序',
  'Sort By: Controversial': '按 有争议 排序',
  'Sort By: Old': '按 旧的 排序',
  'Sort By: Q&A': '按 问答 排序',
  Controversial: '有争议',
  Old: '旧的',
  'Q&A': '问答',
  'Help Center': '帮助中心',
  'Posting to Reddit': '在Reddit上发帖',
  'Remember the human': '记得像个真人一样',
  'Behave like you would in real life': '像在现实生活中一样行为',
  'Look for the original source of content': '寻找内容的原始来源',
  'Search for duplicates before posting': '在发布前搜索重复内容',
  'Read the community’s rules': '阅读社区规则',
  'Add social link': '添加社交平台链接',
  'New Post': '发布新帖子',
  'More Options': '更多设置',
  'Profile Moderation': '个人资料管理',
  'Add to Custom Feed': '添加到自定义订阅',
  'Cake day': '创建日期',
  Karma: '积分',
  'Fewer Options': '更少选项',
  'Edit Post': '编辑帖子',
  'Pin Post To Profile': '将帖子置顶到个人资料',
  Delete: '删除',
  'Mark As NSFW': '标记为敏感内容',
  'Send Me Reply Notifications': '发送给我回复通知',
  Insights: '分析',
  'Total Views': '总浏览量',
  'Upvote Rate': '点赞率',
  'Community Karma': '社区声望',
  'Mark As Spoiler': '标记为剧透',
  'Total Shares': '总分享次数',
  'Changes saved': '更改已保存',
  'Post Insights': '帖子分析',
  'Only you and mods of this community can see this': '只有您和此社区的版主可以看到此内容',
  'VIEW ALL MODERATORS': '查看所有版主',
  Moderators: '版主',
  'Message the mods': '给版主发送消息',
  'Account settings': '账号设置',
  Account: '账号',
  'ACCOUNT PREFERENCES': '账号偏好',
  'Email address': '电子邮件地址',
  'Missing email, please update to secure your account': '缺少电子邮件，请更新以保护您的账号',
  'Change password': '更改密码',
  'Password must be at least 8 characters long': '密码必须至少为8个字符长',
  Gender: '性别',
  'This information may be used to improve your recommendations and ads.': '此信息可能用于改善您的推荐和广告。',
  'Display language': '显示语言 ',
  '(beta)': '(测试版)',
  "Select the language you'd like to experience the Reddit interface in. Note that this won't change the language of user-generated content and that this feature is still in development so translations and UI are still under review.": '选择您想在Reddit界面中显示的语言。请注意，这不会更改用户生成内容的语言，此功能仍在开发中，翻译和用户界面仍在审核中。',
  Change: '更改',
  SELECT: '选择',
  Woman: '女性',
  WOMAN: '女性',
  Man: '男性',
  MAN: '男性',
  'Non-Binary': '非二元性别',
  'NON-BINARY': '非二元性别',
  'I Refer To Myself As...': '我自称为...',
  'I refer to myself as...': '我自称为...',
  'I Prefer Not To Say': '不愿透露',
  'I PREFER NOT TO SAY': '不愿透露',
  Confirm: '确认',
  'Content languages': '内容语言',
  'Add languages you’d like to see posts, community recommendations, and other content in': '添加您想在帖子、社区推荐和其他内容中看到的语言',
  'Location customization': '自定义位置',
  'Specify a location to customize your recommendations and feed. Reddit does not track your precise geolocation data.': '指定一个位置以定制您的推荐和动态。Reddit不会追踪您的精确地理位置数据。',
  'Learn more': '了解更多',
  'Learn More.': '了解更多',
  English: '英语',
  Afrikaans: '南非荷兰语',
  Amharic: '阿姆哈拉语',
  Arabic: '阿拉伯语',
  Armenian: '亚美尼亚语',
  Assamese: '阿萨姆语',
  Azerbaijani: '阿塞拜疆语',
  Basque: '巴斯克语',
  Belarusian: '白俄罗斯语',
  Bengali: '孟加拉语',
  Bosnian: '波斯尼亚语',
  Bulgarian: '保加利亚语',
  Burmese: '缅甸语',
  Catalan: '加泰罗尼亚语',
  'Central Khmer': '高棉语',
  'Chinese (Simplified)': '中文（简体）',
  Croatian: '克罗地亚语',
  Czech: '捷克语',
  Danish: '丹麦语',
  Dutch: '荷兰语',
  Estonian: '爱沙尼亚语',
  Filipino: '菲律宾语',
  Finnish: '芬兰语',
  French: '法语',
  Galician: '加利西亚语',
  Georgian: '格鲁吉亚语',
  German: '德语',
  'Greek, Modern': '现代希腊语',
  Gujarati: '古吉拉特语',
  Hebrew: '希伯来语',
  Hindi: '印地语',
  Hungarian: '匈牙利语',
  Icelandic: '冰岛语',
  Indonesian: '印尼语',
  Italian: '意大利语',
  Japanese: '日语',
  Kannada: '卡纳达语',
  Kazakh: '哈萨克语',
  Kirghiz: '吉尔吉斯语',
  Korean: '韩语',
  Lao: '老挝语',
  Latvian: '拉脱维亚语',
  Lithuanian: '立陶宛语',
  Macedonian: '马其顿语',
  Malay: '马来语',
  Malayalam: '马拉雅拉姆语',
  Marathi: '马拉地语',
  Mongolian: '蒙古语',
  Nepali: '尼泊尔语',
  'Northern Sámi': '北萨米语',
  Norwegian: '挪威语',
  Oriya: '奥里亚语',
  Persian: '波斯语',
  Polish: '波兰语',
  Portuguese: '葡萄牙语',
  Punjabi: '旁遮普语',
  Romanian: '罗马尼亚语',
  Russian: '俄语',
  Sango: '桑戈语',
  Serbian: '塞尔维亚语',
  Sinhala: '僧伽罗语',
  Slovak: '斯洛伐克语',
  Slovenian: '斯洛文尼亚语',
  Spanish: '西班牙语',
  Swahili: '斯瓦希里语',
  Swedish: '瑞典语',
  Tamil: '泰米尔语',
  Telugu: '泰卢固语',
  Thai: '泰语',
  Turkish: '土耳其语',
  Ukrainian: '乌克兰语',
  Urdu: '乌尔都语',
  Uzbek: '乌兹别克语',
  Vietnamese: '越南语',
  'See content in more languages': '查看更多语言的内容',
  'Update your settings to make it easier to discover content in up to 10 languages': '更新您的设置，以便更轻松地在多达10种语言中发现内容',
  'Use approximate location (based on IP)': '使用大致位置（基于IP）',
  'No location specified': '未指定位置',
  Afghanistan: '阿富汗',
  'Aland Islands': '奥兰群岛',
  Albania: '阿尔巴尼亚',
  Algeria: '阿尔及利亚',
  'American Samoa': '美属萨摩亚',
  Andorra: '安道尔',
  Angola: '安哥拉',
  Anguilla: '安圭拉',
  Antarctica: '南极洲',
  'Antigua and Barbuda': '安提瓜和巴布达',
  Argentina: '阿根廷',
  Armenia: '亚美尼亚',
  Aruba: '阿鲁巴',
  Australia: '澳大利亚',
  Austria: '奥地利',
  Azerbaijan: '阿塞拜疆',
  Bahamas: '巴哈马',
  Bahrain: '巴林',
  Bangladesh: '孟加拉国',
  Barbados: '巴巴多斯',
  Belarus: '白俄罗斯',
  Belgium: '比利时',
  Belize: '伯利兹',
  Benin: '贝宁',
  Bermuda: '百慕大',
  Bhutan: '不丹',
  Bolivia: '玻利维亚',
  'Bonaire, Sint Eustatius and Saba': '博内尔、圣尤斯特歇斯和萨巴',
  'Bosnia and Herzegovina': '波斯尼亚和黑塞哥维那',
  Botswana: '博茨瓦纳',
  'Bouvet Island': '布韦岛',
  Brazil: '巴西',
  'British Indian Ocean Territory': '英属印度洋领地',
  'Brunei Darussalam': '文莱',
  Bulgaria: '保加利亚',
  'Burkina Faso': '布基纳法索',
  Burundi: '布隆迪',
  Cambodia: '柬埔寨',
  Cameroon: '喀麦隆',
  Canada: '加拿大',
  'Cape Verde': '佛得角',
  'Cayman Islands': '开曼群岛',
  'Central African Republic': '中非共和国',
  Chad: '乍得',
  Chile: '智利',
  'Christmas Island': '圣诞岛',
  'Cocos (Keeling) Islands': '科科斯（基林）群岛',
  Colombia: '哥伦比亚',
  Comoros: '科摩罗',
  'Congo, Republic of the': '刚果共和国',
  'Congo, The Democratic Republic of the': '刚果民主共和国',
  'Cook Islands': '库克群岛',
  'Costa Rica': '哥斯达黎加',
  "Cote d'Ivoire": '科特迪瓦',
  Croatia: '克罗地亚',
  Cuba: '古巴',
  Curacao: '库拉索',
  Cyprus: '塞浦路斯',
  'Czech Republic': '捷克共和国',
  Denmark: '丹麦',
  Djibouti: '吉布提',
  Dominica: '多米尼克',
  'Dominican Republic': '多米尼加共和国',
  Ecuador: '厄瓜多尔',
  Egypt: '埃及',
  'El Salvador': '萨尔瓦多',
  'Equatorial Guinea': '赤道几内亚',
  Eritrea: '厄立特里亚',
  Estonia: '爱沙尼亚',
  Eswatini: '斯威士兰',
  Ethiopia: '埃塞俄比亚',
  'Falkland Islands (Malvinas)': '福克兰群岛',
  'Faroe Islands': '法罗群岛',
  Fiji: '斐济',
  Finland: '芬兰',
  France: '法国',
  'French Guiana': '法属圭亚那',
  'French Polynesia': '法属波利尼西亚',
  'French Southern Territories': '法属南部领地',
  Gabon: '加蓬',
  Gambia: '冈比亚',
  Georgia: '格鲁吉亚',
  Germany: '德国',
  Ghana: '加纳',
  Gibraltar: '直布罗陀',
  Greece: '希腊',
  Greenland: '格陵兰',
  Grenada: '格林纳达',
  Guadeloupe: '瓜德罗普',
  Guam: '关岛',
  Guatemala: '危地马拉',
  Guernsey: '根西岛',
  Guinea: '几内亚',
  'Guinea-Bissau': '几内亚比绍',
  Guyana: '圭亚那',
  Haiti: '海地',
  'Heard Island and McDonald Islands': '赫德岛和麦克唐纳群岛',
  Honduras: '洪都拉斯',
  'Hong Kong': '香港',
  Hungary: '匈牙利',
  Iceland: '冰岛',
  India: '印度',
  Indonesia: '印度尼西亚',
  Iran: '伊朗',
  Iraq: '伊拉克',
  Ireland: '爱尔兰',
  'Isle of Man': '马恩岛',
  Israel: '以色列',
  Italy: '意大利',
  Jamaica: '牙买加',
  Japan: '日本',
  Jersey: '泽西岛',
  Jordan: '约旦',
  Kazakhstan: '哈萨克斯坦',
  Kenya: '肯尼亚',
  Kiribati: '基里巴斯',
  Kosovo: '科索沃',
  Kuwait: '科威特',
  Kyrgyzstan: '吉尔吉斯斯坦',
  Laos: '老挝',
  Latvia: '拉脱维亚',
  Lebanon: '黎巴嫩',
  Lesotho: '莱索托',
  Liberia: '利比里亚',
  Libya: '利比亚',
  Liechtenstein: '列支敦士登',
  Lithuania: '立陶宛',
  Luxembourg: '卢森堡',
  Macao: '澳门',
  Macedonia: '北马其顿',
  Madagascar: '马达加斯加',
  Malawi: '马拉维',
  Malaysia: '马来西亚',
  Maldives: '马尔代夫',
  Mali: '马里',
  Malta: '马耳他',
  'Marshall Islands': '马绍尔群岛',
  Martinique: '马提尼克',
  Mauritania: '毛里塔尼亚',
  Mauritius: '毛里求斯',
  Mayotte: '马约特',
  Mexico: '墨西哥',
  Micronesia: '密克罗尼西亚',
  Moldova: '摩尔多瓦',
  Monaco: '摩纳哥',
  Mongolia: '蒙古',
  Montenegro: '黑山',
  Montserrat: '蒙特塞拉特',
  Morocco: '摩洛哥',
  Mozambique: '莫桑比克',
  Myanmar: '缅甸',
  Namibia: '纳米比亚',
  Nauru: '瑙鲁',
  Nepal: '尼泊尔',
  Netherlands: '荷兰',
  'New Caledonia': '新喀里多尼亚',
  'New Zealand': '新西兰',
  Nicaragua: '尼加拉瓜',
  Niger: '尼日尔',
  Nigeria: '尼日利亚',
  Niue: '纽埃',
  'Norfolk Island': '诺福克岛',
  'Northern Mariana Islands': '北马里亚纳群岛',
  Norway: '挪威',
  Oman: '阿曼',
  Pakistan: '巴基斯坦',
  Palau: '帕劳',
  'Palestinian Territory': '巴勒斯坦领土',
  Panama: '巴拿马',
  'Papua New Guinea': '巴布亚新几内亚',
  Paraguay: '巴拉圭',
  Peru: '秘鲁',
  Philippines: '菲律宾',
  Pitcairn: '皮特凯恩群岛',
  Poland: '波兰',
  Portugal: '葡萄牙',
  'Puerto Rico': '波多黎各',
  Qatar: '卡塔尔',
  Reunion: '留尼汪',
  Romania: '罗马尼亚',
  Russia: '俄罗斯',
  Rwanda: '卢旺达',
  'Saint Barthelemey': '圣巴泰勒米',
  'Saint Helena': '圣赫勒拿',
  'Saint Kitts and Nevis': '圣基茨和尼维斯',
  'Saint Lucia': '圣卢西亚',
  'Saint Martin': '圣马丁',
  'Saint Pierre and Miquelon': '圣皮埃尔和密克隆',
  'Saint Vincent and the Grenadines': '圣文森特和格林纳丁斯',
  Samoa: '萨摩亚',
  'San Marino': '圣马力诺',
  'Sao Tome and Principe': '圣多美和普林西比',
  'Saudi Arabia': '沙特阿拉伯',
  Senegal: '塞内加尔',
  Serbia: '塞尔维亚',
  Seychelles: '塞舌尔',
  'Sierra Leone': '塞拉利昂',
  Singapore: '新加坡',
  'Sint Maarten': '圣马丁',
  Slovakia: '斯洛伐克',
  Slovenia: '斯洛文尼亚',
  'Solomon Islands': '所罗门群岛',
  Somalia: '索马里',
  'South Africa': '南非',
  'South Georgia and the South Sandwich Islands': '南乔治亚岛和南桑威奇群岛',
  'South Korea': '韩国',
  'South Sudan': '南苏丹',
  Spain: '西班牙',
  'Sri Lanka': '斯里兰卡',
  Sudan: '苏丹',
  Suriname: '苏里南',
  'Svalbard and Jan Mayen': '斯瓦尔巴群岛和扬马延岛',
  Sweden: '瑞典',
  Switzerland: '瑞士',
  Syria: '叙利亚',
  Taiwan: '台湾',
  Tajikistan: '塔吉克斯坦',
  Tanzania: '坦桑尼亚',
  Thailand: '泰国',
  'Timor-Leste': '东帝汶',
  Togo: '多哥',
  Tokelau: '托克劳',
  Tonga: '汤加',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  Tunisia: '突尼斯',
  Turkey: '土耳其',
  Turkmenistan: '土库曼斯坦',
  'Turks and Caicos Islands': '特克斯和凯科斯群岛',
  Tuvalu: '图瓦卢',
  Uganda: '乌干达',
  Ukraine: '乌克兰',
  'United Arab Emirates': '阿拉伯联合酋长国',
  'United Kingdom': '英国',
  'United States': '美国',
  'United States Minor Outlying Islands': '美国本土外小岛屿',
  Uruguay: '乌拉圭',
  Uzbekistan: '乌兹别克斯坦',
  Vanuatu: '瓦努阿图',
  'Vatican City (Holy See)': '梵蒂冈城（教廷）',
  Venezuela: '委内瑞拉',
  Vietnam: '越南',
  'Virgin Islands, British': '英属维尔京群岛',
  'Virgin Islands, U.S.': '美属维尔京群岛',
  'Wallis and Futuna': '瓦利斯和富图纳',
  'Western Sahara': '西撒哈拉',
  Yemen: '也门',
  Zambia: '赞比亚',
  Zimbabwe: '津巴布韦',
  'Other country': '其他国家',
  'CONNECTED ACCOUNTS': '已关联的账号',
  'Connect to Twitter': '关联Twitter',
  'Connect a Twitter account to enable the choice to tweet your new posts and display a link on your profile. We will never post to Twitter without your permission.': '关联Twitter账号，启用推文新帖的选择，并在您的个人资料上显示链接。我们绝不会未经您的许可而发布到Twitter。',
  'Show link on profile': '在个人资料上显示链接',
  'You can show a link to your Twitter account on your profile': '您可以在个人资料上显示关联到您的Twitter账号',
  'Connect to Apple': '关联Apple',
  'Connect account to log in to Reddit with Apple': '关联账号以使用Apple登录Reddit',
  'Connect to Google': '关联Google',
  'Connect account to log in to Reddit with Google': '关联账号以使用Google登录Reddit',
  'BETA TESTS': '测试版',
  'Opt into beta tests': '选择参与测试版',
  'See the newest features from Reddit and join the r/beta community': '查看 Reddit 的最新功能并加入 r/beta 社区',
  'Opt out of the redesign': '退出重新设计',
  'Revert back to old Reddit for the time being': '暂时返回旧版 Reddit',
  'DELETE ACCOUNT': '删除账号',
  'delete account': '删除账号',
  'Safety & Privacy': '安全与隐私',
  'Feed Settings': '动态设置',
  Notifications: '通知',
  Emails: '邮件',
  Subscriptions: '订阅',
  'Chat & Messaging': '聊天与消息',
  'Customize profile': '自定义个人资料',
  'PROFILE INFORMATION': '个人资料信息',
  'Display name (optional)': '显示名称（可选）',
  'Set a display name. This does not change your username.': '设置显示名称。这不会更改您的用户名。',
  'About (optional)': '关于（可选）',
  Optional: '选项',
  'A brief description of yourself shown on your profile.': '在您的个人资料上显示的个人简介。',
  'Social links (5 max)': '社交平台链接（最多5个）',
  'People who visit your profile will see your social links.': '访问您个人资料的人将看到您的社交平台链接。',
  IMAGES: '图片',
  'Avatar and banner image': '头像和横幅图片',
  'Images must be .png or .jpg format': '图片必须是 .png 或 .jpg 格式',
  'PROFILE CATEGORY': '个人资料类别',
  NSFW: '成人内容',
  'This content is NSFW (may contain nudity, pornography, profanity or inappropriate content for those under 18)': '此内容为成人内容（可能包含裸露、色情、粗俗或不适合18岁以下人士的内容）',
  ADVANCED: '高级',
  'Allow people to follow you': '允许其他人关注您',
  'Followers will be notified about posts you make to your profile and see them in their home feed.': '关注者将收到有关您在个人资料上发布的帖子的通知，并在他们的主页中看到这些帖子。',
  'Content visibility': '内容可见性',
  'Posts to this profile can appear in': '此个人资料的帖子可以显示在 ',
  'and your profile can be discovered in': ' 并且您的个人资料可以在 ',
  'Active in communities visibility': '在个人资料上显示我参与的社区',
  'Show which communities I am active in on my profile.': '在我的个人资料上显示我参与的社区。',
  'Clear history': '清除历史记录',
  'Delete your post views history.': '删除您的帖子浏览历史。',
  'PROFILE MODERATION': '个人资料管理',
  'For moderation tools please visit our': '有关管理工具，请访问我们的 ',
  'Profile Moderation page': '个人资料管理页面',
  'Manage how we use data to personalize your Reddit experience, and control how other redditors interact with you. To learn more, visit our ': '管理我们如何使用数据来个性化您的 Reddit 体验，并控制其他 Reddit 用户与您互动的方式。了解更多信息，请访问我们的 ',
  'Privacy & Security FAQs': '隐私与安全常见问题解答',
  SAFETY: '安全',
  'People You’ve Blocked': '您已屏蔽的人',
  'Blocked people can’t send you chat requests or private messages.': '被屏蔽的人无法向您发送聊天请求或私信。',
  'BLOCK NEW USER': '屏蔽新用户',
  "Communities You've Muted": '您已屏蔽的社区',
  "Posts from muted communities won't show up in your feeds or recommendations.": '来自被屏蔽社区的帖子不会出现在您的动态或推荐中。',
  'MUTE NEW COMMUNITY': '屏蔽新社区',
  PRIVACY: '隐私',
  'Show up in search results': '在搜索结果中显示',
  'Allow search engines like Google to link to your profile in their search results.': '允许像 Google 这样的搜索引擎在其搜索结果中链接到您的个人资料。',
  'Personalize ads on Reddit based on information and activity from our partners.': '根据来自我们合作伙伴的信息和活动个性化 Reddit 上的广告。',
  'Allow us to use information from our partners to show you better ads on Reddit.': '允许我们使用来自合作伙伴的信息向您展示更好的 Reddit 广告。',
  'SENSITIVE ADVERTISING CATEGORIES': '敏感广告类别',
  ADD: '添加',
  REMOVE: '移除',
  'You can limit ads about these topics. We’ll do our best not to show them to you when you are signed into your Reddit account.': '您可以限制关于这些主题的广告。我们将尽力在您登录 Reddit 帐户时不向您显示它们。',
  Alcohol: '酒精',
  Allowed: '允许',
  Dating: '约会',
  Gambling: '赌博',
  'Pregnancy and parenting': '怀孕和育儿',
  'Weight loss': '减肥',
  'ADVANCED SECURITY': '高级安全性',
  'Use two-factor authentication': '使用二步验证验证',
  'Help protect your account (even if someone gets your password) by requiring a verification code and a password to log in.': '通过要求验证代码和密码登录，帮助保护您的帐户（即使有人获得了您的密码）。',
  'Manage third-party app authorization': '管理第三方应用程序授权',
  'Limited by you': '由您限制',
  'Feed settings': '动态设置',
  'CONTENT PREFERENCES': '内容偏好设置',
  'Show mature (18+) content': '显示成人（18+）内容',
  'See NSFW (Not Safe for Work) mature and adult images, videos, written content, and other media in your Reddit feeds and search results.': '在您的 Reddit 动态和搜索结果中查看敏感内容和成人图像、视频、文字内容和其他媒体。',
  'Blur mature images and media': '模糊敏感图片和媒体',
  'Blur previews and thumbnails for any images or videos tagged as NSFW (Not Safe for Work).': '对标记为 NSFW（不适于工作场所）的图像或视频的预览和缩略图进行模糊处理。',
  'Enable home feed recommendations': '启用首页动态推荐',
  'Allow us to introduce recommended posts in your home feed.': '允许我们在您的首页动态中推荐帖子。',
  'Autoplay media': '自动播放媒体',
  'Play videos and gifs automatically when in the viewport.': '在可见区域中时自动播放视频和 GIF。',
  'Reduce Animations': '减少动画',
  'Reduce animations on posts, comments, and feeds.': '减少帖子、评论和动态上的动画。',
  'Community themes': '社区主题',
  'Use custom themes for all communities. You can also turn this off on a per community basis.': '为所有社区使用自定义主题。您还可以在每个社区基础上关闭此功能。',
  'Community content sort': '社区内容排序',
  'Choose how you would like content organized in communities you visit. This will not affect global feeds such as Home, or Popular.': '选择您希望在访问的社区中组织内容的方式。这不会影响主页或热门等全局动态。',
  'Remember per community': '记住每个社区设定',
  'Enable if you would like each community to remember and use the last content sort you selected for that community.': '如果您希望每个社区记住并使用您为该社区选择的上次内容排序，请启用此选项。',
  'Global content view': '全局内容视图',
  'Choose how you would like content displayed in feeds. This control is also found above your feed.': '选择您希望在动态中显示内容的方式。此控件还位于您的动态上方。',
  'Enable if you would like each community to remember and use the last content view you selected for that community.': '如果您希望每个社区记住并使用您为该社区选择的上次内容视图，请启用此选项。',
  'Open posts in new tab': '在新标签页中打开帖子',
  'Enable to always open posts in a new tab.': '启用后，将始终在新标签页中打开帖子。',
  'POST PREFERENCES': '帖子偏好设置',
  'Default to markdown': '默认使用 Markdown',
  'When posting, your input will default to markdown text instead of fancy pants.': '在发布时，您的编辑器将默认为 Markdown 文本而不是fancy pants。',
  'Notification settings': '通知设置',
  MESSAGES: '消息',
  'Private messages': '私信',
  'Chat messages': '聊天消息',
  'Chat requests': '聊天请求',
  ACTIVITY: '活动',
  'Community alerts': '社区提示',
  'Mentions of u/username': '@用户名 提及',
  'Comments on your posts': '对您的帖子的评论',
  'Upvotes on your posts': '您帖子的赞',
  'Replies to your comments': '回复您的评论',
  'Activity on your comments': '您评论的活动',
  "Activity on chat posts you're in": '您所在聊天帖子的活动',
  'New followers': '新关注者',
  'Awards you receive': '您获得的奖励',
  'Posts you follow': '您关注的帖子',
  'Comments you follow': '您关注的评论',
  RECOMMENDATIONS: '推荐',
  'Trending posts': '热门帖子',
  'Community recommendations': '社区推荐',
  ReReddit: '转发',
  'Featured content': '精选内容',
  UPDATES: '更新',
  'Reddit announcements': 'Reddit 公告',
  MODERATION: '管理',
  Moderation: '管理',
  'Mod notifications': '版主通知',
  Back: '返回',
  Frequent: '频繁',
  FREQUENT: '频繁',
  Low: '低',
  LOW: '低',
  OFF: '关闭',
  Off: '关闭',
  'Off:': '关闭',
  'Success! You will see fewer notifications from this community in the future.': '成功！您将来将收到较少来自该社区的通知。',
  'Followed! Now you’ll get updates on new activity': '已关注！现在您将收到有关新活动的更新',
  'Unfollowed. You won’t get updates on new activity anymore.': '已取消关注。您将不再收到有关新活动的更新。',
  'Notifications: Low': '通知：低',
  'Notifications: High Frequency': '通知：高频',
  'Notifications: Off': '通知：关闭',
  'Manage Emails': '管理电子邮件',
  'New user welcome': '新用户欢迎',
  'Upvotes on your comments': '您评论的赞',
  'Username mentions': '用户名提及',
  NEWSLETTERS: '新闻简报',
  'Daily Digest': '每日摘要',
  'Unsubscribe from all emails': '取消订阅所有电子邮件',
  'Reddit Premium is a subscription membership that upgrades your account with extra features.': 'Reddit Premium 是一种订阅会员，可为您的帐户提供额外的功能升级。',
  'SUBSCRIPTION STATUS': '订阅状态',
  'Get Reddit Premium and help support Reddit.': '获取 Reddit Premium 并帮助支持 Reddit。',
  'Get Premium': '获取高级会员',
  'Who can send you chat requests': '谁可以向您发送聊天请求',
  EVERYONE: '所有人',
  'Who can send you private messages': '谁可以向您发送私信',
  'Heads up—Reddit admins and moderators of communities you’ve joined can message you even if they’re not approved.': '注意—即使未经批准，Reddit 管理员和您加入的社区的版主也可以向您发送消息。',
  'Mark all as read': '全部标记为已读',
  'Mark all conversations and invites as read.': '将所有对话和邀请标记为已读。',
  'Mark as Read': '标记为已读',
  'Create a community': '创建社区',
  Name: '名称',
  'Community names including capitalization cannot be changed.': '社区名称（包括大小写）无法更改。',
  'Community type': '社区类型',
  Public: '公共',
  'Anyone can view, post, and comment to this community': '任何人都可以查看、发布和评论此社区',
  Restricted: '受限',
  'Anyone can view this community, but only approved users can post': '任何人都可以查看此社区，但只有获批准的用户可以发布',
  Private: '私密',
  'Only approved users can view and submit to this community': '只有获批准的用户才能查看和提交到此社区',
  'Adult content': '成人内容',
  '18+ year old community': '18 岁以上的社区',
  'Grow your community': '发展您的社区',
  'Time to make your first post!': '是时候发表您的第一篇帖子了！',
  'Now that you’ve created your community, start things off right by making your first post.': '既然您已经创建了您的社区，请通过发表您的第一篇帖子来正确开始事情。',
  'Make Your First Post': '发表您的第一篇帖子',
  'Recruit more members': '招募更多成员',
  'Learn how to use invitations to bring more members and moderators to your community.': '了解如何使用邀请将更多成员和版主引入您的社区。',
  'Learn More': '了解更多',
  'There are no posts in this subreddit': '此子社区中没有帖子',
  'Be the first to till this fertile land.': '成为第一个耕耘这片肥沃土地的人。',
  'Add a post': '添加帖子',
  Activism: '社会运动',
  'Addiction Support': '戒毒支持',
  'Animals and Pets': '动物与宠物',
  Anime: '动漫',
  Art: '艺术',
  'Beauty and Makeup': '美容与化妆',
  'Cars and Motor Vehicles': '汽车和机动车辆',
  'Crafts and DIY': '手工艺品和自制',
  'Culture, Race, and Ethnicity': '文化、种族和族裔',
  'Ethics and Philosophy': '伦理学和哲学',
  'Family and Relationships': '家庭和关系',
  Fashion: '时尚',
  'Fitness and Nutrition': '健身和营养',
  'Food and Drink': '食品与饮料',
  'Funny/Humor': '搞笑/幽默',
  游戏: '游戏',
  性别: '性别',
  History: '历史',
  Hobbies: '爱好',
  'Home and Garden': '家居和花园',
  'Internet Culture and Memes': '互联网文化和迷因',
  Law: '法律',
  'Learning and Education': '学习和教育',
  'Marketplace and Deals': '市场和交易',
  'Mature Themes and Adult Content': '成熟主题和成人内容',
  'Medical and Mental Health': '医疗和心理健康',
  "Men's Health": '男性健康',
  Military: '军事',
  Movies: '电影',
  Music: '音乐',
  'Outdoors and Nature': '户外和自然',
  Place: '地点',
  'Podcasts and Streamers': '播客和主播',
  Politics: '政治',
  Programming: '编程',
  'Reading, Writing, and Literature': '阅读、写作和文学',
  'Religion and Spirituality': '宗教和灵性',
  Science: '科学',
  'Sexual Orientation': '性取向',
  'Tabletop Games': '桌面游戏',
  Technology: '技术',
  'Trauma Support': '创伤支持',
  Travel: '旅行',
  "Women's Health": '女性健康',
  'World News': '世界新闻',
  'None of these topics': '无此主题',
  'Add subtopics': '添加子主题',
  'About Community': '关于社区',
  'Mod tools': '版主工具',
  'Add description': '添加描述',
  'Community topics': '社区主题',
  'Add To Custom Feed': '添加到自定义订阅',
  'Add To Favorites': '添加到收藏夹',
  'SUGGESTED TOPICS': '建议主题',
  'Community topics saved!': '社区主题已保存！',
  'Subreddit settings updated successfully': '子社区设置已成功更新',
  'Add community to Custom Feed': '将社区添加到自定义订阅',
  '+ Create a custom feed': '+ 创建自定义订阅',
  Update: '更新',
  'NEW CUSTOM FEED': '新建自定义订阅',
  create: '创建',
  'Custom feed created!': '自定义订阅已创建！',
  'Get the best of': '获取最佳内容',
  'Get updates': '获取更新',
  'Not now': '暂时不需要',
  'Remove From Favorites': '从收藏夹中移除',
  People: '用户',
  Posts: '帖子',
  posts: '帖子',
  'Safe Search': '安全搜索',
  Follow: '关注',
  Following: '已关注',
  Unfollow: '取消关注',
  Leave: '退出',
  Sort: '排序',
  Relevance: '相关性',
  'Go to thread': '查看帖文',
  Time: '时间',
  'All Time': '所有时间',
  'Past Year': '过去一年',
  'Past Month': '过去一个月',
  'Past Week': '过去一周',
  'Past 24 Hours': '过去24小时',
  'Past Hour': '过去1小时',
  'SEE ALL': '查看全部',
  Messages: '消息',
  'Mod Queue': '版主队列',
  Modmail: '版主信箱',
  Queues: '队列',
  Reported: '已报告',
  Removed: '已移除',
  Edited: '已编辑',
  Unmoderated: '未经审查',
  'ALL SUBREDDITS': '所有子社区',
  'All subreddits': '所有子社区',
  'NEWEST FIRST': '最新的优先',
  'Newest First': '最新的优先',
  'Oldest First': '最旧的优先',
  'OLDEST FIRST': '最旧的优先',
  'MOST REPORTED FIRST': '最多报告的优先',
  'Most Reported First': '最多报告的优先',
  'POSTS AND COMMENTS': '帖子和评论',
  'Posts And Comments': '帖子和评论',
  'Live Chat Messages': '实时聊天消息',
  POSTS: '帖子',
  'LIVE CHAT MESSAGES': '实时聊天消息',
  'The queue is clean!': '队列已清空！',
  'Kitteh is pleased': '喵喵满意',
  'LAST 7 DAYS INSIGHTS': '过去7天的分析',
  INACTIVE: '不活跃',
  'More Insights': '更多分析',
  'ACTIVELY BEING MODERATED': '正在活跃的版主',
  'No communities are being moderated': '没有社区正在进行管理',
  'Look up above at the “inactive” section to see what communities might require moderation.': '查看上面的“不活跃”部分，了解可能需要管理的社区。',
  'MODERATOR RESOURCES': '版主资源',
  '/ Mod queue': '/ 版主队列',
  'Scheduled Posts': '预排期帖子',
  'Scheduled posts': '预排期帖子',
  'User Management': '用户管理',
  'Rules and Removal Reasons': '规则和移除原因',
  'User Flair': '用户标识',
  'Content Controls': '内容控制',
  'Mod Log': '版主日志',
  Automod: '自动版主',
  Safety: '安全性',
  CONTENT: '内容',
  Wiki: '维基',
  'Post Flair': '帖子标识',
  'COMMUNITY APPS': '社区应用',
  'Installed Apps': '已安装的应用',
  'Browse Apps': '浏览应用',
  SETTINGS: '设置',
  'General Settings': '常规设置',
  'Posts and Comments': '帖子和评论',
  'Community Appearance': '社区外观',
  'Content Rating': '内容评级',
  Emojis: '表情符号',
  SUPPORT: '支持',
  'Reddit for Community': '社区的Reddit',
  'Mod Help Center': '版主帮助中心',
  'Mod Code of Conduct': '版主行为准则',
  ModSupport: '版主支持',
  ModHelp: '版主帮助',
  'Contact Reddit': '联系Reddit',
  'Exit mod tools': '退出版主工具',
  'Moderator Mail': '版主邮件',
  Inbox: '收件箱',
  'In Progress': '进行中',
  Archived: '已存档',
  Filtered: '已过滤',
  'Ban Appeals': '封禁上诉',
  'Join Request': '加入请求',
  Highlighted: '已突出显示',
  'Mod Discussions': '版主讨论',
  'Communities by': '按',
  Activity: '活跃度',
  'Member Count': '成员数量',
  'moderator added': '版主已添加',
  Help: '帮助',
  Terms: '条款',
  'Recently Updated': '最近更新',
  Unread: '未读',
  Mod: '版主',
  User: '用户',
  'Advanced Search': '高级搜索',
  Highlight: '突出显示',
  Archive: '存档',
  'Mark Unread': '标记为未读',
  'Join Requests': '加入请求',
  'Message title & body': '消息标题和正文',
  'Subreddit name': '子社区名称',
  'Mod name': '版主名称',
  'User name': '用户名称',
  'Message author': '消息作者',
  'Action author': '操作作者',
  'Update type': '更新类型',
  From: '从',
  To: '到',
  Notification: '通知',
  'Mod only': '仅限版主',
  'Message type': '消息类型',
  'Action history': '操作历史',
  'Message state': '消息状态',
  Mute: '屏蔽',
  CLEAR: '清除',
  SEARCH: '搜索',
  'SCHEDULE POST': '计划发布',
  'RECURRING POSTS': '定期发布',
  'Recurring posts': '定期发布',
  'No recurring posts': '没有定期发布',
  'SCHEDULE RECURRING POST': '计划定期发布',
  'Schedule Post': '计划发布',
  "Oh no! We didn't load your topics. Please try again.": '哦，不好！我们没有加载您的主题。请重试。',
  Retry: '重试',
  'The queue is all yours': '队列完全属于您',
  'We’ll let you know if another mod joins you in moderating the community.': '如果另一个版主加入您共同管理社区，我们会通知您。',
  'Last Action taken': '上次操作',
  'Spam Filtered': '垃圾过滤',
  'Has Reports': '有举报',
  'Self Posts': '自帖',
  'Posts With Flair': '带有标识的帖子',
  'Chat Posts': '聊天帖',
  Banned: '已封禁',
  Muted: '已屏蔽',
  Approved: '已批准',
  'Ban user': '封禁用户',
  'views not available': '浏览次数不可用',
  'uniques not available': '独立访客数不可用',
  'subscribed not available': '已订阅不可用',
  'unsubscribed not available': '已取消订阅不可用',
  'Data is not available.': '数据不可用。',
  'The timeframe you selected doesn’t\n        have enough data.': '您选择的时间范围没有足够的数据。',
  'Community Growth': '社区增长',
  'Team Health': '团队健康',
  'Reports & Removals': '举报和移除',
  Pageviews: '页面浏览量',
  Uniques: '独立访客数',
  'Members Growth': '  成员增长',
  'The timeframe you selected doesn’t have enough data.': '您选择的时间范围没有足够的数据。',
  'Ways to impact this': '影响这个的方式',
  'Help people with similar interests discover your community': '帮助有相似兴趣的人发现您的社区',
  'Copied link to your community!': '已复制到您社区的链接！',
  'Share link to your community with others': '与其他人分享您社区的链接',
  'Make it discoverable': '使其可被发现',
  'Edit topics related to your community, so that other people can easily find it': '编辑与您社区相关的主题，以便其他人能够轻松找到它',
  'Last Daily Update': '上次日常更新',
  'Last 7 Days': '过去7天',
  'Last 30 Days': '过去30天',
  'Last 12 Months': '过去12个月',
  '24 Hours View': '24小时查看',
  '7 Days View': '7天查看',
  '30 Days View': '30天查看',
  '12 Months View': '12个月查看',
  'Total Members': '总人数',
  Rules: '规则',
  'Removal Reasons': '移除原因',
  'Reorder rules': '重新排序规则',
  'Add rule': '添加规则',
  'No rules yet': '暂无规则',
  Setup: '设置',
  Assign: '分配',
  Settings: '设置',
  Reorder: '重新排序',
  Add: '添加',
  'CSS class': 'CSS类',
  'Flair ID': '标识',
  "You don't have any user flair yet": '您还没有用户标识',
  'Add visual titles and treatments to the usernames of people who contribute to your community.': '为为您社区做出贡献的人的用户名添加视觉标题和效果。',
  'Start Using User Flair': '开始使用用户标识',
  'Enable user flair': '启用用户标识',
  'Let users to assign their own user flair': '允许用户分配自己的用户标识',
  'Allows users to add, edit, and remove flair to their usernames. (Must be turned on for communities that require user flair.)': '允许用户添加、编辑和删除他们的用户名的标识。（在需要用户标识的社区中必须打开）',
  'Want to learn more about user flair and what settings are best for your community?': '想了解更多关于用户标识以及什么设置最适合您社区的信息？',
  'Visit the Mod Help Center': '访问 Mod 帮助中心',
  'Add flair background': '添加标识背景',
  'FLAIR APPEARANCE': '标识外观',
  'Flair text': '标识文本',
  'FLAIR SETTINGS': '标识设置',
  'Allow user edits': '允许用户编辑',
  'Error: text or emoji is required': '错误：需要文本或表情符号',
  'Discard new flair?': '放弃新标识？',
  'You have a new flair that has not been saved, do you wish to discard this new flair?': '您有一个尚未保存的新标识，您是否要放弃这个新标识？',
  Discard: '放弃',
  'COPY ID': '复制 ID',
  EDIT: '编辑',
  'Content controls': '内容控制',
  'Set requirements and restrictions for how people post and comment in your community': '为用户在社区中发布和评论的方式设置要求和限制',
  'Post Requirements': '帖子要求',
  'Provide members with posting guidelines': '为成员提供发布准则',
  'Posting guidelines let people who are new to your community or posting for the first time know what your expectations are. If you have specific flair or formatting requirements for posts, this is the place to make it clear what you’d like.': '发布准则可让初次访问您的社区或首次发布的用户了解您的期望。如果对帖子有特定的标识或格式要求，这是明确您期望的地方。',
  'Require words in the post title': '要求帖子标题中包含的单词',
  'Posts without these words in the title can’t be submitted. (Choose up to 15 words, 40 characters each.)': '标题中不包含这些单词的帖子将无法提交。（最多选择 15 个单词，每个单词 40 个字符。）',
  'Ban words from the post title': '禁止帖子标题中的单词',
  'Posts with these words in the title can’t be submitted. (Choose up to 15 words, 40 characters each.)': '标题中包含这些单词的帖子将无法提交。（最多选择 15 个单词，每个单词 40 个字符。）',
  'Ban words from the post body': '禁止帖子正文中的单词',
  'Posts with these words in the body can’t be submitted. (Choose up to 15 words, 40 characters each.)': '正文中包含这些单词的帖子将无法提交。（最多选择 15 个单词，每个单词 40 个字符。）',
  'Require or ban links from specific domains': '要求或禁止来自特定域的链接',
  'Posts with links that don’t fit your requirements can’t be submitted.': '链接不符合您的要求的帖子将无法提交。',
  'Restrict how often the same link can be posted': '限制相同链接的发布频率',
  'Posts that have a link that has already been posted to your community cannot be submitted within the number of days you select.': '具有已在您的社区中发布的链接的帖子将无法在您选择的天数内提交。',
  'Advanced post requirements': '高级帖子要求',
  'Require post flair': '要求帖子标识',
  'Posts without flair can’t be submitted. (Note that this requirement is ignored if your community hasn’t set up flair yet.)': '没有标识的帖子将无法提交。（请注意，如果您的社区尚未设置标识，则将忽略此要求。）',
  'Post text body': '帖子正文',
  'Allow posts to have body text': '允许帖子有正文',
  'Text body is optional for all post types': '对于所有类型的帖子，文本正文是可选的',
  'Text body is required for text-only posts': '只有文本的帖子需要正文',
  'Text body is not allowed': '不允许正文',
  'Restrict post title length': '限制帖子标题长度',
  'Set a minimum and/or maximum post title length': '设置最小和/或最大帖子标题长度',
  'Use title text RegEx requirements': '使用标题文本正则表达式要求',
  'Use regular expressions for more advanced title matching. These use the': '使用正则表达式进行更高级的标题匹配。这些使用 ',
  'Use body text RegEx requirements': '使用正文文本正则表达式要求',
  'Use regular expressions for more advanced body text matching. These use the': '使用正则表达式进行更高级的正文文本匹配。这些使用 ',
  'Python RegEx syntax': 'Python 正则表达式语法',
  'Save changes': '保存更改',
  'FILTER BY': '按条件筛选',
  'TIME FRAME': '时间范围',
  MODERATOR: '版主',
  ACTIONS: '操作',
  USERNAME: '用户名',
  'POST URL': '帖子网址',
  Type: '类型',
  Action: '操作',
  Details: '详情',
  'Back to mod tools': '返回到版主工具',
  'Create new page': '创建新页面',
  'Recent wiki revisions': '最近的维基修订',
  'Add wiki contributors': '添加维基贡献者',
  'Ban wiki contributors': '禁止维基贡献者',
  'Wiki settings': '维基设置',
  '"config/automoderator" does not exist': '"config/automoderator" 不存在',
  'Create a wiki page from this URL': '从此URL创建维基页面',
  'CREATE PAGE': '创建页面',
  'Add a reason for your revision': '为您的修订添加原因',
  'REVISION REASON': '例如：在附录中添加了来源',
  View: '查看',
  'Recent revisions': '最近的修改',
  TIME: '时间',
  'WIKI PAGE': '维基页面',
  'View page history': '查看页面历史',
  'View page source': '查看页面源代码',
  'View in community': '在社区中查看',
  'Copy URL': '复制网址',
  'Page settings': '页面设置',
  Edit: '编辑',
  'This page is empty': '此页面为空',
  'Edit it to add some content': '编辑以添加内容',
  'EDIT PAGE': '编辑页面',
  'Add contributor': '添加贡献者',
  'Added wiki contributors': '已添加维基贡献者',
  'Ban contributor': '封禁贡献者',
  'Banned wiki contributors': '已封禁维基贡献者',
  'COMMUNITY WIKI PAGES': '社区维基页面',
  'Wikis can be edited by': '维基可以被以下人编辑',
  'Karma required to edit and create wiki pages': '编辑和创建维基页面所需的声望值',
  'Age of Reddit account required to edit and create wiki pages': '编辑和创建维基页面所需的 Reddit 帐户年限',
  'ADVANCED SETTINGS': '高级设置',
  'Settings for old site': '旧站点的设置',
  'To change settings that influence the old site, you must go to the old settings page': '要更改影响旧站点的设置，您必须转到旧的设置页面',
  'Safety & privacy settings': '安全与隐私设置',
  'Exclude posts by site-wide banned users': '排除全站封禁用户的帖子',
  'Posts are excluded from modqueue/unmoderated': '帖子被排除在modqueue/unmoderated之外',
  'Modmail filtered folder': 'Modmail过滤文件夹',
  'Automatically filters inbound modmail messages that are likely to contain harassment.': '自动过滤可能包含骚扰的传入版主邮件消息。',
  'Ban evasion filter': '封禁逃逸过滤器',
  'Filter content from suspected ban evaders.': '过滤来自疑似封禁逃逸者的内容。',
  'Mature content filter': '成人内容过滤器',
  'Filter content likely to contain sexual or graphic media.': '过滤可能包含性或图形媒体的内容。',
  'CROWD CONTROL': '人群控制',
  "Automatically collapse or filter content from people who aren't trusted users within your community yet.": '自动折叠或过滤尚未在您社区中得到信任的人的内容。',
  'Use Crowd Control to automatically collapse comments from users you’re not sure about.': '使用人群控制自动折叠您不确定的用户的评论。',
  Lenient: '宽松',
  Moderate: '适度',
  Strict: '严格',
  'Hold Crowd Controlled comments for review': '将人群控制的评论保留以供审查',
  'Instead of collapsing crowd controlled comments will be held for review in mod queue.': '与其折叠，人群控制的评论将在版主队列中进行审查。',
  'Use Crowd Control to automatically filter posts from users you’re not sure about.': '使用人群控制自动过滤您不确定的用户的帖子。',
  DISCOVER: '发现',
  "Show your community to the general Reddit population or just to people who have similar interests, by adjusting how people can find it. Not sure what's best for you?": '通过调整人们如何发现社区，向Reddit总体人口或只向具有类似兴趣的人展示您的社区。不确定什么对您最好？',
  'Community settings': '社区设置',
  'COMMUNITY PROFILE': '社区资料',
  'Community name': '社区名称',
  'Community description': '社区描述',
  'This is how new members come to understand your community.': '这是新成员了解您社区的方式。',
  'Send welcome message to new members': '向新成员发送欢迎消息',
  'Create a custom welcome message to greet people the instant they join your community. New community members will see this in a direct message 1 hour after joining.': '创建自定义欢迎消息，欢迎新成员加入您的社区。新社区成员将在加入后1小时内在直接消息中看到此消息。',
  'COMMUNITY LOCATION AND MAIN LANGUAGE': '社区位置和主要语言',
  'Adding a location helps your community show up in search results and recommendations and helps local redditors find it easier.': '添加位置有助于使您的社区出现在搜索结果和推荐中，并帮助本地Reddit用户更容易找到它。',
  Language: '语言',
  Region: '地区',
  'COMMUNITY TYPE': '社区类型',
  'Type of Community': '社区类型',
  'When your community is marked as an 18+ community, users must be flagged as 18+ in their user settings': '当您的社区被标记为18+社区时，用户必须在其用户设置中标记为18+。',
  'Show up in high-traffic feeds': '在高流量订阅中显示',
  'Allow your community to be in r/all, r/popular, and trending lists where it can be seen by the general Reddit population.': '允许您的社区出现在r/all、r/popular和趋势列表中，以供Reddit总体人口查看。',
  'Post flair': '帖子标签',
  'Post flair is disabled': '帖子标签已禁用',
  'Post flairs will not be visible until feature is enabled': '在启用功能之前，帖子标签将不可见',
  'Add post flair to tag, label, and organize posts in your community': '为您的社区的帖子添加标签，标签和组织',
  'Start Using Post Flair': '开始使用帖子标签',
  'Get recommended to individual redditors': '推荐给个别Reddit用户',
  'Let Reddit recommend your community to people who have similar interests.': '让Reddit向具有类似兴趣的人推荐您的社区。',
  'Enable post flair': '启用帖子标签',
  "You don't have any post flair yet": '您尚未设置任何帖子标签',
  'Let users give their posts flair': '允许用户为其帖子添加标签',
  'Allows users to add and remove flair from their posts. (Must be turned on for communities that require post flair.)': '允许用户为其帖子添加或删除标签。（必须在需要帖子标签的社区中启用。）',
  'Want to learn more about post flair and what settings are best for your community?': '想了解更多关于帖子标签和适合您社区的设置吗？',
  'Post and Comment settings': '帖子和评论设置',
  'Post type options': '帖子类型选项',
  ANY: '任意',
  Any: '任意',
  'Links Only': '仅链接',
  'LINKS ONLY': '仅链接',
  'Text Posts Only': '仅文本帖子',
  'TEXT POSTS ONLY': '仅文本帖子',
  'Allow crossposting of posts.': '允许帖子的跨贴。',
  'Archive posts': '归档帖子',
  'Don’t allow commenting or voting on posts older than 6 months': '不允许在6个月前的帖子上发表评论或投票',
  'Enable spoiler tag': '启用剧透标签',
  SPOILER: '剧透',
  'Media on posts with the spoiler tag are blurred': '在带有剧透标签的帖子上的媒体将被模糊处理',
  'Allow image uploads and links to image hosting sites': '允许上传图片和链接到图片托管站点',
  'Allow multiple images per post': '允许每篇帖子上传多张图片',
  'Allow polls': '允许投票',
  'Spam filter strength': '垃圾邮件过滤器强度',
  "'HIGH' is the standard filter, 'LOW' disables most filtering, 'ALL' will filter every post initially and they will need to be approved manually to be visible": "'HIGH' 是标准过滤器，'LOW' 禁用大多数过滤，'ALL' 将在初始时过滤每篇帖子，它们需要手动批准才能可见",
  Links: '链接',
  'Low (Default)': '低（默认）',
  'LOW (DEFAULT)': '低（默认）',
  High: '高',
  HIGH: '高',
  All: '全部',
  ALL: '全部',
  'Suggested sort': '建议的排序',
  'All comment feeds in community will default to this sort setting': '社区中的所有评论订阅将默认使用此排序设置',
  'Collapse deleted and removed comments': '折叠已删除和移除的评论',
  'Minutes to hide comment scores': '隐藏评论分数的分钟数',
  'Media in comments': '评论中的媒体',
  'GIFs from GIPHY': '来自GIPHY的GIF',
  'Allow comments with GIFs from GIPHY.': '允许带有来自GIPHY的GIF的评论。',
  'Collectible Expressions': '可收藏表情',
  'Allow comments with Collectible Expressions.': '允许带有可收藏表情的评论。',
  Images: '图片',
  'Allow comments with uploaded images.': '允许带有上传图片的评论。',
  'Allow comments with uploaded GIFs.': '允许带有上传的GIF的评论。',
  Appearance: '外观',
  'Color theme': '颜色主题',
  'Name & icon': '名称和图标',
  Structure: '结构',
  'Menu links': '菜单链接',
  'RESET TO DEFAULTS': '重置为默认值',
  'Sidebar widgets': '侧边栏小部件',
  Banner: '横幅',
  Menu: '菜单',
  'CREATE NEW TAB': '创建新标签',
  'REORDER LINKS': '重新排序链接',
  'ID CARD': '身份证',
  'Community Details': '社区详情',
  'Sidebar widget appearance': '侧边栏小部件外观',
  'Title background color': '标题背景颜色',
  'Widget background color': '小部件背景颜色',
  'ADD WIDGET': '添加小部件',
  'Joined community': '加入社区',
  'Currently viewing community': '当前查看的社区',
  'Community Description': '社区描述',
  'Edit Community Description': '编辑社区描述',
  'Up + Down Vote Icons': '顶部 + 底部投票图标',
  "If you want to upload your own vote icons, you'll need to upload an image for each of the indicated icon states.": '如果您想上传自己的投票图标，您需要为每个指定的图标状态上传一张图片。',
  'Post Background': '帖子背景',
  Color: '颜色',
  Image: '图片',
  'Standard Reddit': '标准Reddit',
  Custom: '自定义',
  'Title Color': '标题颜色',
  'Theme Colors': '主题颜色',
  'Body Background': '正文背景',
  'Inactive upvote': '非活动投票',
  'Active upvote': '活动投票',
  'Upvote count color': '顶部投票计数颜色',
  'Discard unsaved changes before leaving?': '在离开之前放弃未保存的更改？',
  'You have made some changes to your community, do you wish to leave this menu without saving?': '您对社区进行了一些更改，您是否希望在离开此菜单时不保存这些更改？',
  'Inactive downvote': '非活动反对票',
  'Active downvote': '活动反对票',
  'Downvote count color': '底部投票计数颜色',
  'Link Preview Placeholder Image': '链接预览占位图',
  "Most of the time, link posts automatically generate a placeholder image; sometimes they don't. Use the Standard Reddit placeholder, or create your own!": '大多数情况下，链接帖子会自动生成占位图；有时可能不会。使用标准Reddit占位图，或者创建您自己的占位图！',
  'Drag and Drop or Upload Image': '拖放或上传图片',
  'Link Colors': '链接颜色',
  'Active Page': '活动页面',
  'Inactive Page': '非活动页面',
  Hover: '悬停',
  'Main Menu Background': '主菜单背景',
  'Submenu Background': '子菜单背景',
  'Match Main Menu Background': '匹配主菜单背景',
  'Solid Color': '纯色',
  Height: '高度',
  'Small • 64px': '小 • 64像素',
  'Medium • 128px': '中 • 128像素',
  'Large • 192px': '大 • 192像素',
  'Recommended upload size: 4,000x128px': '建议上传尺寸：4,000x128像素',
  'Additional Background Image': '附加背景图像',
  'Mobile banner image': '移动横幅图像',
  'This image will override the banner background image on mobile apps. Removing the mobile banner image will display the banner background image on mobile apps.': '此图像将覆盖移动应用程序上的横幅背景图像。移除移动横幅图像将在移动应用程序上显示横幅背景图像。',
  'Recommended upload size: 1,600x480px': '建议上传尺寸：1,600x480像素',
  'Community Name Format': '社区名称格式',
  'Mod Notifications': '版主通知',
  'Allow Notifications': '允许通知',
  'Turn off to stop any mod notifications from this community': '关闭以停止来自该社区的任何版主通知',
  'Mod Mail': '版主信箱',
  Reports: '举报',
  'COMMUNITY GROWTH': '社区增长',
  'Content Tag': '内容标签',
  'Your content tag is based on a moderator survey about community posts and discussions.': '您的内容标签是基于有关社区帖子和讨论的版主调查。',
  'Set up your tag': '设置您的标签',
  'Take a quick survey to help people know what to expect when they visit this community': '参与快速调查，帮助人们了解访问该社区时可以期待什么',
  Milestones: '里程碑',
  'Cake days and membership milestones': '庆祝 Reddit 年龄和会员里程碑',
  'Posts with Upvotes': '带有赞的帖子',
  'KNOW WHEN POSTS IN YOUR COMMUNITY ARE UPVOTED.': '了解您社区中的帖子何时被点赞。',
  'Allow Notification': '允许通知',
  'Choose how many reports activate a notification': '选择多少举报会触发通知',
  'Advanced Setup': '高级设置',
  'Choose how many upvotes activate a notification': '选择多少赞会触发通知',
  'Tips & Tricks': '提示与技巧',
  'Get tips and reminders to help you grow': '获取有助于增长的提示和提醒',
  'New Posts': '新帖子',
  'Posts with Comments': '带有评论的帖子',
  'ACTIVITY & COMMUNICATIONS': '活动和通讯',
  'Community Icon': '社区图标',
  'Custom Image': '自定义图像',
  'Required Size: 256x256px': '必需尺寸：256x256像素',
  'These community styling options will also display in Reddit apps.': '这些社区样式选项也将显示在Reddit应用中。',
  'Hide Community Icon in Banner': '在横幅中隐藏社区图标',
  'Your Community Icon will still display in other areas of Reddit': '您的社区图标仍将显示在Reddit的其他区域',
  'New Messages': '新消息',
  'Choose how many comments activate a notification': '选择多少评论会触发通知',
  'KNOW WHEN POSTS IN YOUR COMMUNITY ARE GETTING LOTS OF COMMENTS.': '了解您社区中的帖子何时收到大量评论。',
  IMAGE: '图片',
  NAME: '名称',
  'Appears in': '出现在',
  'Badges, Emoji, and more': '徽章、表情符号等',
  'Emoji settings': '表情符号设置',
  'Add emoji': '添加表情符号',
  'Emojis have been disabled for this community': '对于这个社区，表情符号已被禁用',
  'Emojis in flairs will not be displayed, and existing emojis will appear as plain text.': '在标识中的表情符号将不会显示，并且现有的表情符号将显示为纯文本。',
  'Tell a Friend': '告诉朋友',
  'Latest Releases': '最新发布',
  Style: '风格',
  You: '你',
  Recommended: '推荐',
  'See all': '查看全部',
  'Spooky Sequel': '恐怖续集',
  'Explore More': '更多探索',
  Popular: '热门',
  '2023 NFL Season Kickoff Pack': '2023 NFL赛季开幕包',
  'Spooky Sequel Creators': '恐怖续集创作者',
  'Browse The Gallery': '浏览画廊',
  'All Items': '所有物品',
  'All Creators': '所有创作者',
  'By Price': '按价格',
  'Past Drops': '过去的降价',
  'Interested in being a featured creator?': '有兴趣成为特色创作者？',
  'Join the Waitlist': '加入等候名单',
  'Animal Style': '动物风格',
  'Autumn Time': '秋季时光',
  Wearing: '穿戴',
  Shop: '商店',
  shop: '商店',
  Tops: '上装',
  tops: '上装',
  bottoms: '下装',
  Bottoms: '下装',
  hats: '帽子',
  Hats: '帽子',
  face: '面部',
  Face: '面部',
  'left hand': '左手',
  'Left Hand': '左手',
  'right hand': '右手',
  'Right Hand': '右手',
  'full outfits': '全套装',
  'Full Outfits': '全套装',
  body: '身体',
  Body: '身体',
  eyes: '眼睛',
  Eyes: '眼睛',
  hair: '头发',
  Hair: '头发',
  expression: '表情',
  Expression: '表情',
  'facial hair': '胡须',
  'Facial Hair': '胡须',
  'Past Looks': '过去的外观',
  'Revisit one of your looks': '重新查看您的一个外观',
  'SEE FULL IMAGE': '查看完整图像',
  "Because you've shown interest in this community": '因为您对这个社区表现出了兴趣',
  'Your personal Reddit frontpage. Come here to check in with your favorite communities.': '您的个人Reddit首页。来这里查看您最喜欢的社区。',
  'Create Your Own Avatar': '创建您自己的头像',
  'View More': '查看更多',
  Chat: '聊天',
  'See more communities': '查看更多社区',
  'Have an idea for a new community?': '有一个新社区的想法吗？',
  'Popular on Reddit right now': 'Reddit当前热门',
  'Because you visited this community before': '因为您之前访问过这个社区',
  'Show off that karma!': '炫耀一下您的声望值！',
  'Pin a post from your feed using the "..." at the bottom of each post': '使用每篇帖子底部的"..."将帖子置顶在您的动态中',
  'OK, I GOT IT': '好的，我知道了',
  'Pinned Posts': '置顶的帖子',
  "You're a moderator of these communities": '这些是您管理的社区',
  'Insights are only available for 45 days after post creation.': '分析功能仅在帖子创建后的45天内可用。',
  'Create a new post': '创建一个新帖子',
  'and see how it performs!': '并查看其表现！',
  'No Comments Yet': '暂无评论',
  'Be the first to share what you think!': '成为第一个分享您的想法的人！',
  'Comment as': '评论者',
  Comment: '评论',
  'Markdown Mode': 'Markdown 模式',
  'Connect a Twitter account in your User Settings. With a connected account you can choose to share new posts you make directly to Twitter.': '在您的用户设置中连接 Twitter 帐户。通过已连接的帐户，您可以选择将您新发布的帖子直接分享到 Twitter。',
  'You can set Markdown as the default editor mode in the settings': '您可以在设置中将 Markdown 设置为默认编辑器模式',
  'Open Settings': '打开设置',
  'Switch to Fancy Pants Editor': '切换到 Fancy Pants 编辑器',
  'This community requires body text.': '请输入正文。',
  'Please fix the above requirements': '请先按照要求改正内容',
  'Your drafts will live here': '您的草稿将保存在这里',
  Close: '关闭',
  'Something went wrong, please try again': '出了点问题，请重试',
  'Add To Collection': '添加到收藏',
  'Content is an important part of any new community.': '内容是任何新社区的重要组成部分。',
  'Try creating your own post now!': '现在尝试创建您自己的帖子！',
  'Add a Primary Topic': '添加主题',
  Approve: '批准',
  Remove: '移除',
  Spam: '垃圾',
  'Add Community Topics': '添加社区主题',
  'Tell us what topics are relevant to your community so we can surface it to the right users': '告诉我们您社区相关的主题，以便我们将其呈现给合适的用户',
  'Create Collections!': '创建收藏！',
  'Create a series of scheduled events or just group random things. Make something awesome.': '创建一系列定期事件或只是将随机事物分组。创造一些令人惊叹的东西。',
  'Compose a post like normal.': '像平常一样撰写帖子。',
  'Create & name your collection.': '创建并为您的收藏命名。',
  'Add more posts to your collection.': '将更多帖子添加到您的收藏中。',
  'Create a collection': '创建一个收藏',
  'Group posts into one feed. Create a series of events or just a group of random things. Make something awesome!': '将帖子分组到一个源中。创建一系列事件或只是一组随机的事物。创造一些令人惊叹的东西！',
  'Give a title for your collection': '为您的收藏取一个标题',
  Create: '创建',
  'Schedule this post': '安排此帖',
  'Submit Time': '提交时间',
  'Time zone:': '时区：',
  'Repeat Options': '重复选项',
  'Advanced Options': '高级选项',
  'Contest Mode': '竞赛模式',
  'Post as AutoModerator': '作为自动版主发布',
  'Note: This post will be in Scheduled Posts in mod hub and editable.': '注意：此帖将出现在版主中心的计划帖子中，可编辑。',
  'Not A Sticky Post': '不是置顶帖',
  'Submit As First Sticky Post': '提交为第一置顶帖',
  'Submit As Second Sticky Post': '提交为第二置顶帖',
  'Default Comment Order': '默认评论顺序',
  'Not a sticky post': '不是置顶帖',
  'Submit as first sticky post': '提交为第一置顶帖',
  'Submit as second sticky post': '提交为第二置顶帖',
  Apply: '应用',
  Collections: '收藏',
  'Give them access to...': '给予权限给...',
  'Send message': '发送消息',
  'Approve user': '审批用户',
  Access: '权限',
  "(can't edit)": '(无法编辑)',
  Everything: '所有权限',
  'Full access including the ability to manage moderator access and permissions.': '完全访问权限，包括管理版主的访问权和使用权限。',
  'Manage Wiki Pages': '管理 Wiki 页面',
  'Create and manage wiki pages and AutoMod*.': '创建和管理 Wiki 页面和自动版主*。',
  'Create Live Chats': '创建实时聊天',
  'Create live chat posts in this community.': '在此社区创建实时聊天帖子。',
  'Manage Posts & Comments': '管理帖子和评论',
  'Access queues, take action on content, and manage collections and events.': '访问队列，对内容采取行动，管理收藏和事件。',
  'Manage Users': '管理用户',
  'Access mod notes, ban and mute users, and approve submitters*.': '访问版主注释，封禁和静音用户，并批准提交者*。',
  'Manage Mod Mail': '管理版主邮件',
  'Read and respond to modmail and mute users*.': '阅读并回复版主邮件，并对用户进行静音*。',
  'Manage Settings': '管理设置',
  'Manage community settings, appearance, emojis, rules, and AutoMod*.': '管理社区设置、外观、表情符号、规则和自动版主*。',
  'Manage Flair': '管理标识',
  'Create and manage user and post flair.': '创建和管理用户和帖子的标识。',
  'You can edit these moderators': '您可以编辑这些版主',
  'Leave as mod': '保留为版主',
  'Invite user as mod': '邀请用户作为版主',
  '*Note: To manage AutoMod, mods must have access to Wiki Pages and Manage Settings. To mute users, mods must have access to Mod Mail and Manage Users.': '*注：要管理自动版主，版主必须具有对 Wiki 页面和管理设置的访问权限。要对用户进行静音，版主必须具有对版主邮件和管理用户的访问权限。',
  'Reports & Removals Insights are in beta. A small percentage of data may be inaccurate depending on what features your community is opted in to, and the duration between admin actions and mod actions on the same pieces of content.': '报告和移除见解处于测试阶段。根据您的社区选择的功能以及版主操作和版主操作在相同内容上的时间间隔，数据可能有一小部分不准确。',
  'Overview for the last 30 days': '过去30天的概览',
  'Safety filters': '安全过滤器',
  'items filtered': '过滤的项目',
  Removals: '移除',
  'items removed': '已移除的项目',
  'items published': '已发布的项目',
  'Reported content': '被举报的内容',
  'items reported': '被举报的项目',
  'Published and removed posts': '已发布和已移除的帖子',
  'posts published': '已发布的帖子',
  'total posts removed': '总帖子移除数',
  'Reports on posts': '帖子的举报',
  'total reports on posts': '总举报帖子数',
  'Reports by Reason': '按原因举报',
  'Content removed by admins': '管理员移除的内容',
  'Total admin removals': '管理员总移除数',
  'Aligned with mod action': '与版主操作一致',
  'Opposite of mod action': '版主操作的相反',
  'Not reviewed by mods': '未由版主审查',
  'Safety filters monthly overview': '安全过滤器月度概览',
  'No data for the selected time frame': '所选时间范围内无数据',
  'Ban Evasion': '规避封禁',
  'Crowd Control': '群体控制',
  'Published and removed comments': '已发布和已移除的评论',
  'comments published': '已发布的评论',
  'total comments removed': '总评论移除数',
  'Reports on comments': '评论的举报',
  'total reports on comments': '总举报评论数',
  'Character length': '字符长度',
  'Title must match one of:': '标题必须匹配以下之一：',
  'Body must match one of:': '正文必须匹配以下之一：',
  'You do not have any users with user flair': '您没有任何使用用户标识的用户',
  'Search for a user to assign a user flair': '搜索用户以分配用户标识',
  'Username with preview': '带有预览的用户名',
  'Flair template': '标识模板',
  'Restriction type': '限制类型',
  'Required domains': '必需包含域名',
  'Blocked domains': '屏蔽域名',
  'Only allow link posts with these domains': '只允许使用这些域名的链接帖子',
  'Add banned words': '添加禁用的词',
  'Add required words': '添加必需包含的词',
  'Guideline text': '指南文本',
  'Lenient:': '宽松:',
  'Posts from users who have negative karma in your community are automatically held for review in mod queue.': '您社区中负声望用户的帖子将自动在版主队列中进行审查。',
  'Moderate:': '适中:',
  'Posts from new users and users with negative karma in your community are automatically held for review in mod queue.': '新用户和您社区中负声望用户的帖子将自动在版主队列中进行审查。',
  'Strict:': '严格:',
  'Posts from users who haven’t joined your community, new users, and users with negative karma in your community are automatically held for review in mod queue.': '尚未加入您社区的用户、新用户和您社区中负声望用户的帖子将自动在版主队列中进行审查。'
}

let canRun = true
const translate = () => {
  if (canRun) {
    const elements = document.body.querySelectorAll('div, span, button, p, a, h1, h2, h3, h4, h5, label, li, option, strong')

    function processNode (node) {
      if (!node.querySelector('*')) {
        const text = (node.outerText + '').trim()
        if (list[text]) node.innerText = list[text]
        // 帖子评论数
        if (node.className === 'FHCV02u6Cp2zYL0fhQPsO' || node.className === '_vaFo96phV6L5Hltvwcox') {
          node.innerText = text.replace(/comments|comment/gi, '个评论').replace(/upvotes|upvote/g, '个赞同')
        }
        // 版主工具
        if (node.className === '_3V0T64xptTp5xLaY-1nsaz') {
          node.innerText = text.replace('No scheduled posts in', '没有预排期的帖子在')
            .replace('No banned users in', '没有被禁止的用户在')
            .replace('No rules yet', '暂无规则')
            .replace('No mod actions found', '未找到版主操作')
        }
        // 发布时间
        if (node.className === '_2VF2J19pUIMSLJFky-7PEI' || node.className === '_3DP27Wdecz93GDJDLCM9e_' || node.className === 'ThreadPreview__time' || node.className === '_3Uo5d6Bc06NW_l6A8NOkuR' || node.dataset.testid === 'post_timestamp') {
          node.innerText = text.replace(/hours|hour|hr\./g, '小时')
            .replace(/minutes|minute|min./g, '分钟')
            .replace(/days|day/g, '天')
            .replace(/months|month/g, '月')
            .replace(/years|year/g, '年')
            .replace(' ago', '前')
        }
        // 社区创建时间
        if (node.className === '_1d4NeAxWOiy0JPz7aXRI64' || node.id.includes('cakeday')) {
          node.innerText = text.replace('Created', '创建于')
            .replace(/January|Jan/gi, '1月')
            .replace(/February|Feb/gi, '2月')
            .replace(/March|Mar/gi, '3月')
            .replace(/April|Apr/gi, '4月')
            .replace(/May|May/gi, '5月')
            .replace(/June|Jun/gi, '6月')
            .replace(/July|Jul/gi, '7月')
            .replace(/August|Aug/gi, '8月')
            .replace(/September|Sep/gi, '9月')
            .replace(/October|Oct/gi, '10月')
            .replace(/November|Nov/gi, '11月')
            .replace(/December|Dec/gi, '12月')
        }
      } else {
        for (let i = 0; i < node.childNodes.length; i++) {
          const childNode = node.childNodes[i]
          if (childNode.nodeType === Node.ELEMENT_NODE) {
            if (childNode.shadowRoot) {
              // Process nodes in shadow root
              processNode(childNode.shadowRoot)
            } else {
              // Process regular nodes
              processNode(childNode)
            }
          } else if (childNode.nodeType === Node.TEXT_NODE) {
            const newStr = list[childNode.nodeValue.trim()]
            if (newStr) childNode.nodeValue = newStr
          }
        }
      }
    }
    for (const element of elements) processNode(element)
    canRun = false
    setTimeout(() => {
      canRun = true
    }, 100)
  }
}

const observer = new MutationObserver(translate)

observer.observe(document.documentElement, { childList: true, subtree: true })
